/*
 * AMPLIA Lab — page generator
 * _source.html is the single source of truth. This script builds
 *   - index.html: the home page, with only the HOME_SECTIONS below
 *   - one page per section (research.html, team.html, ...)
 * all with the same nav, footer and scripts.
 *
 * After editing _source.html, run:   node build.js
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
// sections shown on the home page (kept in source order)
const HOME_SECTIONS = ["home", "news", "research", "chips-home", "join"];
// title: menu/breadcrumb name · heading: big page title (defaults to title)
// dropHead: remove the section's own heading block (.section-head) on this page
// parts: keep only these <!-- part:NAME --> … <!-- /part:NAME --> blocks of the section
const PAGES = [
  { key: "research",     title: "Research",     sections: ["research"], heading: "Research Interests<br>&amp; On-Going Projects", dropHead: true },
  { key: "professor",    title: "Professor",    sections: ["team"], parts: ["professor"], dropHead: true },
  { key: "team",         title: "Members &amp; Alumni", sections: ["team"], parts: ["people"], dropHead: true },
  { key: "publications", title: "Publications", sections: ["publications"], dropHead: true },
  { key: "gallery",      title: "Chip Gallery", sections: ["gallery"], parts: ["chips"], dropHead: true },
  { key: "teamwork",     title: "Teamwork",     sections: ["gallery"], parts: ["teamwork"], dropHead: true },
  { key: "lectures",     title: "Lectures",     sections: ["lectures"], dropHead: true },
  { key: "contact",      title: "Contact",      sections: ["contact"] }
];

const src = fs.readFileSync(path.join(ROOT, "_source.html"), "utf8");
const mainStart = src.indexOf("<main>");
const mainEnd = src.indexOf("</main>");
if (mainStart < 0 || mainEnd < 0) throw new Error("_source.html: <main> … </main> not found");

const GENERATED = "<!doctype html>\n<!-- Generated by build.js from _source.html. Edit _source.html, then run: node build.js -->";
const head = src.slice(0, mainStart).replace("<!doctype html>", GENERATED);
const tail = src.slice(mainEnd);

function section(id) {
  const m = src.match(new RegExp(`<section[^>]*\\bid="${id}"[\\s\\S]*?</section>`));
  if (!m) throw new Error(`_source.html: <section id="${id}"> not found`);
  return m[0];
}

// section plus the <!-- ==== NAME ==== --> banner comment right above it
function sectionWithBanner(id) {
  const html = section(id);
  const banner = src.slice(0, src.indexOf(html)).match(/<!-- =+ [^=]+ =+ -->\s*$/);
  return (banner ? banner[0] : "") + html;
}

function onlyParts(html, keep) {
  return html.replace(/\n\s*<!-- part:([\w-]+) -->[\s\S]*?<!-- \/part:\1 -->/g, (block, name) => (keep.includes(name) ? block : ""));
}

function withoutHead(html) {
  // from <div class="section-head…"> to the </div> at the same indentation
  return html.replace(/\n( *)<div class="section-head[^"]*">[\s\S]*?\n\1<\/div>\n/, "\n");
}

function pageHero(title, heading) {
  return `<section class="hero hero--page">
  <div class="hero__bg" aria-hidden="true"><svg id="heroBg" viewBox="0 0 1440 640" preserveAspectRatio="xMidYMid slice"></svg></div>
  <div class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><span aria-current="page">${title}</span></nav>
    <h1 class="page-title">${heading}</h1>
  </div>
</section>`;
}

fs.writeFileSync(path.join(ROOT, "index.html"), head + "<main>\n" + HOME_SECTIONS.map(sectionWithBanner).join("\n\n") + "\n" + tail);
console.log("✓ index.html");

for (const p of PAGES) {
  let top = head
    .replace(/<title>[^<]*<\/title>/, `<title>${p.title} · AMPLIA Lab, Inha University</title>`)
    .replace('<body data-page="home">', `<body data-page="${p.key}">`);
  const body = p.sections.map((id) => {
    let html = section(id);
    if (p.parts) html = onlyParts(html, p.parts);
    if (p.dropHead) html = withoutHead(html);
    return html;
  }).join("\n\n");
  const html = top + "<main>\n" + pageHero(p.title, p.heading || p.title) + "\n\n" + body + "\n" + tail;
  fs.writeFileSync(path.join(ROOT, `${p.key}.html`), html);
  console.log(`✓ ${p.key}.html`);
}
